### ISSUE TITLE
Windowの縦方向リサイズに制限あり

### ISSUE THREAD

**Issue by shiology** [drikin/fmb#5]
全画面表示でない普通の状態で、画面を縦方向に大きくしようとすると、下方向には伸ばせる。しかし、そのwindowを画面上端まで移動して、さらに下端をした方向にドラッグしようとしても、のばせない。windowの表示位置が強制的に中央に戻ってしまって、中途半端なサイズまでしかのばせません。

**Comment by drikin** [comment]
フィードバックありがとうございます。Yosemiteの環境で試したところ、いわれていた状況を上手く再現出来ませんでした。（上下方向には自由にリサイズできるように見えます）
もしYosemiteでしたら試しにOption押しながら左から三番目の最大化ボタンを押して、従来のリサイズボタン相当の機能を呼び出したときに上下にリサイズできますでしょうか？

またモニターはセカンドディスプレイ等お使いですか？

**Comment by shiology** [comment]
この現象は下記の2つの環境で同様に発生しています。
・iMac Retina 5Kディスプレイモデルにセカンドディスプレイを接続したメインディスプレイ（セカンドディスプレイでは試していません）。OS X 10.10.3
・MacBook Air 11インチ。OS X 10.10.2

ところが!!　いま試しにMacBook Air 11インチでPRAMクリアしてから試したらできました。昨日は確かにできなかったのに……。明日、研究室に行ったらiMacでも試してみますね!!どうもありがとうございます!!

**Comment by shiology** [comment]
あと、option+緑のボタンも試しました。できました。従来のリサイズボタン機能、こうやって呼び出せるのですね。存じませんでした。重ねてどうもありがとうございます!!

**Comment by shiology** [comment]
研究室に来てiMac 5Kを再起動したら直りました。そもそもiMac 5KでFinderのwindowをリサイズしようとしたら同じ現象が発生したため、上記の問題はfbm固有の問題ではなく、iMac 5KのOS自体に生じていた問題だったようです。ほとんどのアプリを全画面化して使っているので、気づきませんでした。申し訳ございませんでした。現状、fmbはiMac 5KでもMacBook Air 11インチでも、なんな問題もなく動いております。感謝してます!!
